# Generated by Django 4.2.7 on 2023-11-07 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='brithday',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'A user this this phone number already exists.'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989([0-3]|9)\\d{8}$', 'Enter a valid phone number', 'invalid')], verbose_name='phone number'),
        ),
    ]
