# Generated by Django 4.2.7 on 2023-11-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_brithday_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nicked_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nick name'),
        ),
    ]
