# Generated by Django 4.2.7 on 2023-11-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_nicked_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nicked_name',
        ),
    ]
