# Generated by Django 4.2.7 on 2023-11-09 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'A user whith this phone number already exists.'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989([0-3]|9)\\d{8}$', 'Enter a valid phone number', 'invalid')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='avatar'),
        ),
    ]
